"""
Generate a Python script and a Jupyter notebook that reproduce the app's run.

v3: the generated code calls the SAME library functions the app uses
(`utils.preprocessing.preprocess`, `utils.modeling.train_and_evaluate`, ...)
with the exact options the app used, instead of re-implementing the pipeline
in a 600-line template. The old template had already drifted from the app
(e.g. it skipped the app's date-parse-rate check); calling the library makes
drift impossible. The trade-off: the script needs this project's `utils`
package importable - which the saved model bundle needed anyway.
"""

from __future__ import annotations

import json
import pprint
import re
from typing import Any


def _literal(obj: Any) -> str:
    return pprint.pformat(obj, indent=1, width=96, sort_dicts=False)


def _jsonable(obj: Any) -> Any:
    """Keep only literal-safe values (numbers, strings, bools, None, lists, dicts)."""
    if isinstance(obj, dict):
        return {str(k): _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(v) for v in obj]
    if isinstance(obj, (bool, int, float, str)) or obj is None:
        if isinstance(obj, float) and obj != obj:  # NaN
            return None
        return obj
    try:
        import numpy as np
        if isinstance(obj, np.generic):
            return _jsonable(obj.item())
    except Exception:
        pass
    return str(obj)


def generate_python_script(
    *,
    target: str,
    model_names: list[str],
    test_size: float = 0.2,
    random_state: int = 42,
    cv_folds: int = 5,
    cv_strategy: str = "kfold",
    csv_path: str = "your_dataset.csv",
    val_csv_path: str | None = None,
    test_csv_path: str | None = None,
    log_transform_target: bool = False,
    auto_datetime_features: bool = True,
    drop_low_variance: bool = True,
    auto_drop_id_columns: bool = True,
    drop_duplicate_rows: bool = True,
    time_column: str | None = None,
    group_column: str | None = None,
    summary: dict[str, Any] | None = None,
    add_missing_indicators: bool = True,
    add_interactions: bool = False,
    cv_repr: str | None = None,
    selection_metric: str = "rmse",
    selection_note: str = "",
    winner_spec: dict | None = None,
    interval: dict | None = None,
    preprocess_options: dict | None = None,
    smearing_factor: float | None = None,
    app_test_metrics: dict | None = None,
    split_strategy: str | None = None,
) -> str:
    if preprocess_options is None:
        preprocess_options = {
            "test_size": test_size, "random_state": random_state,
            "split_strategy": split_strategy or ("time" if time_column else "random"),
            "time_column": time_column, "group_column": group_column,
            "log_transform_target": bool(log_transform_target),
            "auto_datetime_features": auto_datetime_features,
            "drop_low_variance": drop_low_variance, "auto_drop_id_columns": auto_drop_id_columns,
            "drop_duplicate_rows": drop_duplicate_rows,
            "add_missing_indicators": add_missing_indicators, "add_interactions": add_interactions,
        }
    winner_spec = winner_spec or {"name": "LinearRegression", "params": {}}
    interval = interval or {}
    app_metrics = {k: v for k, v in (app_test_metrics or {}).items()
                   if k in ("RMSE", "MAE", "R2", "MedianAE")}
    summary_str = json.dumps(_jsonable(summary or {}), indent=2)
    header_note = re.sub(r"\s+", " ", selection_note or "").strip()

    script = f'''"""
Regression pipeline - auto-generated by Regression Crew.

Reproduces the app's run with the SAME library code the app uses (this
project's `utils` package), so the script cannot drift from the app.
Run it from the project folder, or set REGRESSION_CREW_DIR to that folder.

Target: {target!r}
Models compared in the app: {model_names}
App winner: {winner_spec.get("name")!r}
How it was chosen: {header_note}
CV scheme used by the app: {cv_repr or cv_strategy}

Preprocessing summary from the app run:
{summary_str}
"""
import os
import sys
import warnings

warnings.filterwarnings("ignore")
PROJECT_DIR = os.environ.get("REGRESSION_CREW_DIR",
                             os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_DIR)

import joblib
import numpy as np
import pandas as pd

from utils.io import read_table
from utils.modeling import (
    BASELINE_MODEL_NAME,
    _compute_metrics,
    apply_smearing,
    filter_zoo_for_data,
    get_default_model_zoo,
    rebuild_estimator,
    train_and_evaluate,
)
from utils.preprocessing import preprocess

# ---------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------
TRAIN_CSV    = {csv_path!r}
VAL_CSV      = {val_csv_path!r}
TEST_CSV     = {test_csv_path!r}
TARGET       = {target!r}
RANDOM_STATE = {random_state}
N_FOLDS      = {cv_folds}
CV_STRATEGY  = {cv_strategy!r}
SELECTION_METRIC = {selection_metric!r}
# the exact preprocessing options the app used (after its automatic decisions)
PREPROCESS_OPTIONS = {_literal(_jsonable(preprocess_options))}
# the app's final winner: model name + final settings (after tuning / fixes)
WINNER_SPEC = {_literal(_jsonable(winner_spec))}
# bias correction for log-target models (None = not used)
SMEARING_FACTOR = {smearing_factor!r}
# what the app reported on the test rows, for comparison
APP_TEST_METRICS = {_literal(_jsonable(app_metrics))}
# {int(interval.get("coverage_target", 0.9) * 100)}% conformal interval half-width measured by the app ({interval.get("space", "original")} space)
INTERVAL_HALFWIDTH = {interval.get("halfwidth", 0.0)!r}
# set True to re-run the whole model comparison (slower)
RUN_FULL_COMPARISON = False

# ---------------------------------------------------------------------
# 1. LOAD
# ---------------------------------------------------------------------
df_train = read_table(TRAIN_CSV)
df_val   = read_table(VAL_CSV) if VAL_CSV else None
df_test  = read_table(TEST_CSV) if TEST_CSV else None
print(f"Train: {{df_train.shape}}")

# ---------------------------------------------------------------------
# 2. PREPROCESS
# ---------------------------------------------------------------------
pre = preprocess(df_train, TARGET, df_val=df_val, df_test=df_test, **PREPROCESS_OPTIONS)
s = pre.summary
print(f"Split: {{s['split_strategy_used']}} | train {{s['n_train']}} / test {{s['n_test']}} rows"
      f" | {{s['n_features_after']}} features | target transform: {{pre.target_transform}}")
if s.get("id_like_columns_dropped"):
    print("Dropped row-counter / ID columns:", s["id_like_columns_dropped"])
if s.get("numeric_string_columns_parsed"):
    print("Parsed formatted numbers in:", s["numeric_string_columns_parsed"])

# ---------------------------------------------------------------------
# 3. REBUILD AND EVALUATE THE APP'S WINNER
# ---------------------------------------------------------------------
winner = rebuild_estimator(WINNER_SPEC, pre.preprocessor_templates, random_state=RANDOM_STATE,
                           time_ordered=CV_STRATEGY == "time",
                           target_transform=pre.target_transform)
common = dict(cv_folds=N_FOLDS, cv_strategy=CV_STRATEGY, groups_train=pre.groups_train,
              target_transform=pre.target_transform, X_val=pre.X_val_raw, y_val=pre.y_val,
              random_state=RANDOM_STATE, selection_metric=SELECTION_METRIC,
              preprocessor=pre.preprocessor_templates, tuning="off",
              auto_remediate=False, build_ensemble=False, capacity_probe=False)
res = train_and_evaluate(pre.X_train_raw, pre.X_test_raw, pre.y_train, pre.y_test,
                         models={{WINNER_SPEC["name"]: winner}}, **common)[WINNER_SPEC["name"]]
pred = res.y_pred_test
if pre.target_transform == "log1p" and SMEARING_FACTOR:
    pred = apply_smearing(res.y_pred_test_model, SMEARING_FACTOR)
WINNER_TEST_METRICS = _compute_metrics(pre.y_test_original, pred)
m = res.metrics
print(f"\\n{{WINNER_SPEC['name']}}: CV {{SELECTION_METRIC.upper()}} "
      f"{{m.get('CV_' + SELECTION_METRIC.upper() + '_mean', float('nan')):.4f}}")
for k in ("RMSE", "MAE", "R2"):
    app = APP_TEST_METRICS.get(k)
    print(f"  test {{k}}: {{WINNER_TEST_METRICS[k]:.6g}}" + (f"   (app: {{app:.6g}})" if app is not None else ""))

# ---------------------------------------------------------------------
# 4. OPTIONAL FULL MODEL COMPARISON
# ---------------------------------------------------------------------
if RUN_FULL_COMPARISON:
    zoo = get_default_model_zoo(RANDOM_STATE, time_ordered=CV_STRATEGY == "time",
                                target_transform=pre.target_transform)
    zoo, skipped = filter_zoo_for_data(zoo, pre.y_train_original,
                                       target_transform=pre.target_transform)
    all_results = train_and_evaluate(pre.X_train_raw, pre.X_test_raw, pre.y_train, pre.y_test,
                                     models=zoo, **{{**common, "build_ensemble": True,
                                                     "capacity_probe": True}})
    key = "CV_" + SELECTION_METRIC.upper() + "_mean"
    table = pd.DataFrame([{{"Model": n, "CV": r.metrics.get(key), "test RMSE": r.metrics["RMSE"],
                           "test R2": r.metrics["R2"], "fit": r.fit_status}}
                          for n, r in all_results.items()]).sort_values("CV")
    print(table.to_string(index=False))

# ---------------------------------------------------------------------
# 5. PLOTS
# ---------------------------------------------------------------------
try:
    import matplotlib.pyplot as plt
    y_true = pre.y_test_original
    resid = y_true - pred
    fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
    axes[0].scatter(y_true, pred, alpha=0.55, edgecolor="none")
    lo, hi = min(y_true.min(), pred.min()), max(y_true.max(), pred.max())
    axes[0].plot([lo, hi], [lo, hi], "r--")
    axes[0].set_title(f"{{WINNER_SPEC['name']}} - Predicted vs Actual")
    axes[1].scatter(pred, resid, alpha=0.55, edgecolor="none", color="#10b981")
    axes[1].axhline(0, color="r", linestyle="--")
    axes[1].set_title("Residuals vs Predicted")
    axes[2].hist(resid, bins=40, color="#8b5cf6", alpha=0.85)
    axes[2].set_title("Residual distribution")
    plt.tight_layout(); plt.savefig("diagnostics_final_model.png", dpi=110); plt.show()
except ImportError:
    print("matplotlib not installed - skipping plots")

# ---------------------------------------------------------------------
# 6. SAVE best_model.joblib
# ---------------------------------------------------------------------
joblib.dump({{"preprocessor": pre.raw_feature_builder, "model": res.estimator,
             "model_name": WINNER_SPEC["name"], "target": TARGET,
             "target_transform": pre.target_transform, "smearing_factor": SMEARING_FACTOR,
             "prediction_interval": {{"halfwidth": INTERVAL_HALFWIDTH}}}}, "best_model.joblib")
print("\\nSaved best_model.joblib (use utils.modeling.predict_with_interval to predict)")
'''
    return script


def generate_notebook(**kwargs) -> str:
    """Same content as the script, one notebook cell per numbered section."""
    script = generate_python_script(**kwargs)
    dash = "# " + "-" * 69
    pattern = re.compile(re.escape(dash) + r"\n# (.+)\n" + re.escape(dash) + r"\n")
    pieces = pattern.split(script)
    cells: list[dict[str, Any]] = []

    def md(text):
        cells.append({"cell_type": "markdown", "metadata": {}, "source": [text]})

    def code(text):
        text = text.strip("\n")
        if text.strip():
            cells.append({"cell_type": "code", "metadata": {}, "execution_count": None,
                          "outputs": [], "source": (text + "\n").splitlines(keepends=True)})

    md("# End-to-end regression pipeline\n*Auto-generated by Regression Crew. "
       "Runs the same library code as the app.*\n")
    intro = pieces[0].replace('os.path.dirname(os.path.abspath(__file__))', 'os.getcwd()')
    code(intro)
    for title, body in zip(pieces[1::2], pieces[2::2]):
        md(f"## {title.strip()}\n")
        code(body)
    nb = {
        "cells": cells,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                     "language_info": {"name": "python", "version": "3.11"}},
        "nbformat": 4, "nbformat_minor": 5,
    }
    return json.dumps(nb, indent=1)
