"""
Generate a self-contained Python script and Jupyter notebook that
reproduce the entire pipeline, reflecting every option chosen in the UI.
"""

from __future__ import annotations

import json
from typing import Any


def _model_construction_lines(model_names: list[str], use_xgb: bool, use_lgbm: bool) -> str:
    template = {
        "LinearRegression": "LinearRegression()",
        "Ridge":            "Ridge(alpha=1.0, random_state=RANDOM_STATE)",
        "Lasso":            "Lasso(alpha=0.01, random_state=RANDOM_STATE, max_iter=10000)",
        "ElasticNet":       "ElasticNet(alpha=0.01, l1_ratio=0.5, random_state=RANDOM_STATE, max_iter=10000)",
        "DecisionTree":     "DecisionTreeRegressor(random_state=RANDOM_STATE, max_depth=10)",
        "RandomForest":     "RandomForestRegressor(n_estimators=200, random_state=RANDOM_STATE, n_jobs=-1)",
        "GradientBoosting": "GradientBoostingRegressor(n_estimators=200, random_state=RANDOM_STATE)",
        "KNN":              "KNeighborsRegressor(n_neighbors=5, n_jobs=-1)",
        "SVR":              "SVR(kernel='rbf', C=1.0, gamma='scale')",
        "XGBoost":          "XGBRegressor(n_estimators=300, learning_rate=0.05, max_depth=6, random_state=RANDOM_STATE, n_jobs=-1, verbosity=0)",
        "LightGBM":         "LGBMRegressor(n_estimators=300, learning_rate=0.05, num_leaves=31, random_state=RANDOM_STATE, n_jobs=-1, verbosity=-1)",
    }
    return "\n".join(f'    "{n}": {template[n]},'
                     for n in model_names if n in template)


def _imports_block(model_names: list[str]) -> str:
    extra = []
    if "XGBoost"  in model_names: extra.append("from xgboost import XGBRegressor")
    if "LightGBM" in model_names: extra.append("from lightgbm import LGBMRegressor")
    return "\n".join(extra)


def generate_python_script(
    *,
    target: str,
    model_names: list[str],
    test_size: float = 0.2,
    random_state: int = 42,
    cv_folds: int = 5,
    cv_strategy: str = "kfold",
    csv_path: str = "your_dataset.csv",
    val_csv_path: str | None = None,
    test_csv_path: str | None = None,
    log_transform_target: bool = False,
    auto_datetime_features: bool = True,
    drop_low_variance: bool = True,
    auto_drop_id_columns: bool = True,
    time_column: str | None = None,
    group_column: str | None = None,
    summary: dict[str, Any] | None = None,
) -> str:
    summary_str = json.dumps(summary or {}, indent=2)
    models_block = _model_construction_lines(
        model_names, use_xgb="XGBoost" in model_names, use_lgbm="LightGBM" in model_names
    )
    extra_imports = _imports_block(model_names)
    multi_file = test_csv_path is not None
    has_val = val_csv_path is not None
    log_target = log_transform_target

    if cv_strategy == "time":
        cv_import_extra = "TimeSeriesSplit"
        cv_constructor  = f"TimeSeriesSplit(n_splits={cv_folds})"
    elif cv_strategy == "group":
        cv_import_extra = "GroupKFold"
        cv_constructor  = f"GroupKFold(n_splits={cv_folds})"
    else:
        cv_import_extra = "KFold"
        cv_constructor  = f"KFold(n_splits={cv_folds}, shuffle=True, random_state=RANDOM_STATE)"

    script = f'''"""
End-to-end regression pipeline (auto-generated by Regression Crew).

Target: {target!r}
Models: {model_names}

Pipeline summary from the original UI run:
{summary_str}
"""
import warnings
warnings.filterwarnings("ignore")

import time
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, cross_val_score, {cv_import_extra}
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import ElasticNet, Lasso, LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.metrics import (mean_absolute_error, mean_squared_error,
                             median_absolute_error, r2_score)
{extra_imports}

# ---------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------
TRAIN_CSV    = {csv_path!r}
VAL_CSV      = {val_csv_path!r}
TEST_CSV     = {test_csv_path!r}
TARGET       = {target!r}
TEST_SIZE    = {test_size}
RANDOM_STATE = {random_state}
N_FOLDS      = {cv_folds}
LOG_TARGET   = {log_target}
AUTO_DATETIME_FEATURES = {auto_datetime_features}
DROP_LOW_VARIANCE      = {drop_low_variance}
AUTO_DROP_ID_COLUMNS   = {auto_drop_id_columns}
TIME_COLUMN  = {time_column!r}
GROUP_COLUMN = {group_column!r}
HIGH_CARDINALITY_THRESHOLD = 20
ID_COLUMN_NAME_HINTS = ("unnamed:", "id", "index", "rowid", "row_id", "row_num", "_id")

# ---------------------------------------------------------------------
# 1. LOAD
# ---------------------------------------------------------------------
df_train = pd.read_csv(TRAIN_CSV)
df_val   = pd.read_csv(VAL_CSV)  if VAL_CSV  else None
df_test  = pd.read_csv(TEST_CSV) if TEST_CSV else None
print(f"Train: {{df_train.shape}}")
if df_val  is not None: print(f"Val:   {{df_val.shape}}")
if df_test is not None: print(f"Test:  {{df_test.shape}}")

# drop rows where target is missing
df_train = df_train.dropna(subset=[TARGET])
if df_val  is not None: df_val  = df_val.dropna(subset=[TARGET])
if df_test is not None: df_test = df_test.dropna(subset=[TARGET])
assert pd.api.types.is_numeric_dtype(df_train[TARGET]), "Target must be numeric."

# ---------------------------------------------------------------------
# 1.5 DROP ID-LIKE COLUMNS (e.g. pandas' "Unnamed: 0" — leaks when sorted)
# ---------------------------------------------------------------------
def is_id_like(s):
    if not pd.api.types.is_numeric_dtype(s): return False
    if s.nunique(dropna=True) != s.notna().sum(): return False
    arr = s.dropna().to_numpy()
    if not np.all(arr == arr.astype(np.int64)): return False
    return s.is_monotonic_increasing or s.is_monotonic_decreasing

if AUTO_DROP_ID_COLUMNS:
    id_cols = []
    for col in df_train.columns:
        if col == TARGET or col == TIME_COLUMN: continue
        if any(h in col.lower() for h in ID_COLUMN_NAME_HINTS) or is_id_like(df_train[col]):
            id_cols.append(col)
    if id_cols:
        df_train = df_train.drop(columns=id_cols)
        if df_val  is not None: df_val  = df_val.drop( columns=[c for c in id_cols if c in df_val.columns])
        if df_test is not None: df_test = df_test.drop(columns=[c for c in id_cols if c in df_test.columns])
        print(f"Dropped ID/index columns: {{id_cols}}")

# ---------------------------------------------------------------------
# 2. AUTO DATETIME FEATURE EXTRACTION
# ---------------------------------------------------------------------
def extract_datetime(frame, cols):
    out = frame.copy()
    for col in cols:
        if col not in out.columns:
            continue
        parsed = pd.to_datetime(out[col], errors="coerce")
        out[f"{{col}}_year"]    = parsed.dt.year
        out[f"{{col}}_month"]   = parsed.dt.month
        out[f"{{col}}_day"]     = parsed.dt.day
        out[f"{{col}}_weekday"] = parsed.dt.weekday
        if parsed.dt.hour.fillna(0).sum() > 0:
            out[f"{{col}}_hour"] = parsed.dt.hour
        out = out.drop(columns=[col])
    return out

datetime_cols = []
if AUTO_DATETIME_FEATURES:
    for col in df_train.columns:
        if col == TARGET: continue
        s = df_train[col]
        if pd.api.types.is_datetime64_any_dtype(s):
            datetime_cols.append(col)
        elif pd.api.types.is_object_dtype(s) or pd.api.types.is_string_dtype(s):
            parsed = pd.to_datetime(s, errors="coerce")
            if parsed.notna().sum() / max(s.notna().sum(), 1) > 0.85:
                datetime_cols.append(col)
    if datetime_cols:
        df_train = extract_datetime(df_train, datetime_cols)
        if df_val  is not None: df_val  = extract_datetime(df_val,  datetime_cols)
        if df_test is not None: df_test = extract_datetime(df_test, datetime_cols)
        print(f"Extracted datetime features from: {{datetime_cols}}")

# ---------------------------------------------------------------------
# 3. DROP LOW-VARIANCE COLUMNS
# ---------------------------------------------------------------------
if DROP_LOW_VARIANCE:
    drop = [c for c in df_train.columns
            if c != TARGET and df_train[c].nunique(dropna=True) <= 1]
    if drop:
        df_train = df_train.drop(columns=drop)
        if df_val  is not None: df_val  = df_val.drop( columns=[c for c in drop if c in df_val.columns])
        if df_test is not None: df_test = df_test.drop(columns=[c for c in drop if c in df_test.columns])
        print(f"Dropped low-variance columns: {{drop}}")

# ---------------------------------------------------------------------
# 4. SPLIT
# ---------------------------------------------------------------------
if df_test is not None:
    train_df, test_df = df_train, df_test
    val_df = df_val
elif TIME_COLUMN and TIME_COLUMN in df_train.columns:
    sorted_df = df_train.sort_values(TIME_COLUMN).reset_index(drop=True)
    cut = int(len(sorted_df) * (1 - TEST_SIZE))
    train_df, test_df = sorted_df.iloc[:cut], sorted_df.iloc[cut:]
    val_df = None
    print(f"Time-aware split on '{{TIME_COLUMN}}'")
else:
    train_df, test_df = train_test_split(df_train, test_size=TEST_SIZE,
                                         random_state=RANDOM_STATE)
    val_df = None

groups_train = None
if GROUP_COLUMN and GROUP_COLUMN in train_df.columns:
    groups_train = train_df[GROUP_COLUMN].values
    train_df = train_df.drop(columns=[GROUP_COLUMN])
    if test_df is not None and GROUP_COLUMN in test_df.columns:
        test_df = test_df.drop(columns=[GROUP_COLUMN])
    if val_df is not None and GROUP_COLUMN in val_df.columns:
        val_df = val_df.drop(columns=[GROUP_COLUMN])

# also drop the time column from features once it's served its splitting purpose
if TIME_COLUMN and TIME_COLUMN in train_df.columns:
    train_df = train_df.drop(columns=[TIME_COLUMN])
    test_df  = test_df.drop( columns=[TIME_COLUMN])
    if val_df is not None: val_df = val_df.drop(columns=[TIME_COLUMN])

y_train = train_df[TARGET].values.astype(float)
y_test  = test_df [TARGET].values.astype(float)
y_val   = val_df  [TARGET].values.astype(float) if val_df is not None else None
X_train = train_df.drop(columns=[TARGET])
X_test  = test_df .drop(columns=[TARGET])
X_val   = val_df  .drop(columns=[TARGET]) if val_df is not None else None

# ---------------------------------------------------------------------
# 5. ENCODE / IMPUTE / SCALE
# ---------------------------------------------------------------------
numeric_cols, low_card_cat, high_card_cat = [], [], []
for col in X_train.columns:
    if pd.api.types.is_numeric_dtype(X_train[col]):
        numeric_cols.append(col)
    elif X_train[col].nunique(dropna=True) > HIGH_CARDINALITY_THRESHOLD:
        high_card_cat.append(col)
    else:
        low_card_cat.append(col)

# frequency-encode high-card categoricals using TRAIN frequencies
for col in high_card_cat:
    freq = X_train[col].astype(object).value_counts(normalize=True)
    X_train[col] = X_train[col].map(freq).fillna(0.0)
    X_test [col] = X_test [col].map(freq).fillna(0.0)
    if X_val is not None:
        X_val[col] = X_val[col].map(freq).fillna(0.0)
    numeric_cols.append(col)

numeric_pipe = Pipeline([
    ("impute", SimpleImputer(strategy="median")),
    ("scale",  StandardScaler()),
])
cat_pipe = Pipeline([
    ("impute", SimpleImputer(strategy="most_frequent")),
    ("encode", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])
transformers = []
if numeric_cols:  transformers.append(("num", numeric_pipe, numeric_cols))
if low_card_cat:  transformers.append(("cat", cat_pipe,     low_card_cat))
preprocessor = ColumnTransformer(transformers, remainder="drop")

X_train = preprocessor.fit_transform(X_train)
X_test  = preprocessor.transform(X_test)
if X_val is not None: X_val = preprocessor.transform(X_val)
print(f"After preprocessing: {{X_train.shape[1]}} features, "
      f"{{X_train.shape[0]}} train / {{X_test.shape[0]}} test rows")

# ---------------------------------------------------------------------
# 6. OPTIONAL TARGET LOG-TRANSFORM (y -> log1p(y))
# ---------------------------------------------------------------------
y_train_orig, y_test_orig = y_train.copy(), y_test.copy()
if LOG_TARGET and (y_train >= 0).all() and (y_test >= 0).all():
    y_train = np.log1p(y_train)
    y_test  = np.log1p(y_test)
    if y_val is not None: y_val = np.log1p(y_val)
    print("Applied log1p transform to target.")

# ---------------------------------------------------------------------
# 7. TRAIN ALL MODELS
# ---------------------------------------------------------------------
models = {{
{models_block}
}}

def safe_mape(y_true, y_pred):
    mask = y_true != 0
    if not mask.any(): return float("nan")
    return float(np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100)

def compute_metrics(y_true, y_pred):
    return {{
        "MAE":      mean_absolute_error(y_true, y_pred),
        "RMSE":     np.sqrt(mean_squared_error(y_true, y_pred)),
        "R2":       r2_score(y_true, y_pred),
        "MedianAE": median_absolute_error(y_true, y_pred),
        "MAPE_pct": safe_mape(y_true, y_pred),
    }}

cv = {cv_constructor}
results = {{}}
for name, est in models.items():
    print(f"Training {{name}}...")
    t0 = time.time()
    est.fit(X_train, y_train)
    elapsed = time.time() - t0

    y_pred_test_raw = est.predict(X_test)
    y_pred_test = np.expm1(y_pred_test_raw) if LOG_TARGET else y_pred_test_raw

    metrics = compute_metrics(y_test_orig, y_pred_test)
    metrics["train_time_sec"] = elapsed
    try:
        kw = {{"groups": groups_train}} if GROUP_COLUMN and groups_train is not None else {{}}
        cv_r2 = cross_val_score(est, X_train, y_train, cv=cv, scoring="r2", n_jobs=-1, **kw)
        metrics["CV_R2_mean"] = float(cv_r2.mean())
        metrics["CV_R2_std"]  = float(cv_r2.std())
    except Exception:
        pass
    results[name] = {{"estimator": est, "y_pred_test": y_pred_test, "metrics": metrics}}

# ---------------------------------------------------------------------
# 8. RANK + REPORT
# ---------------------------------------------------------------------
metrics_df = pd.DataFrame(
    [{{"Model": n, **r["metrics"]}} for n, r in results.items()]
).sort_values("RMSE")
print("\\n=== Model comparison (sorted by RMSE) ===")
print(metrics_df.to_string(index=False))
best_name = metrics_df.iloc[0]["Model"]
print(f"\\n>>> Best model: {{best_name}}")

# ---------------------------------------------------------------------
# 9. PLOTS
# ---------------------------------------------------------------------
sns.set_theme(style="whitegrid")

# comparison: RMSE
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=metrics_df, x="Model", y="RMSE", ax=ax, palette="viridis")
ax.set_title("Model comparison — RMSE (lower is better)")
plt.xticks(rotation=30, ha="right"); plt.tight_layout()
plt.savefig("comparison_rmse.png", dpi=110); plt.show()

# per-model diagnostics
for name, r in results.items():
    y_pred = r["y_pred_test"]
    residuals = y_test_orig - y_pred
    fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
    axes[0].scatter(y_test_orig, y_pred, alpha=0.55, edgecolor="none")
    lo, hi = min(y_test_orig.min(), y_pred.min()), max(y_test_orig.max(), y_pred.max())
    axes[0].plot([lo, hi], [lo, hi], "r--")
    axes[0].set_title(f"{{name}} — Predicted vs Actual")
    axes[0].set_xlabel("Actual"); axes[0].set_ylabel("Predicted")
    axes[1].scatter(y_pred, residuals, alpha=0.55, edgecolor="none", color="#10b981")
    axes[1].axhline(0, color="r", linestyle="--")
    axes[1].set_title(f"{{name}} — Residuals vs Predicted")
    axes[1].set_xlabel("Predicted"); axes[1].set_ylabel("Residual")
    axes[2].hist(residuals, bins=40, color="#8b5cf6", alpha=0.85)
    axes[2].set_title(f"{{name}} — Residual Distribution")
    axes[2].set_xlabel("Residual"); axes[2].set_ylabel("Frequency")
    plt.tight_layout(); plt.savefig(f"diagnostics_{{name}}.png", dpi=110); plt.show()

# ---------------------------------------------------------------------
# 10. PERSIST BEST MODEL
# ---------------------------------------------------------------------
import joblib
best = results[best_name]["estimator"]
joblib.dump({{"preprocessor": preprocessor, "model": best,
             "target_transform": "log1p" if LOG_TARGET else "none",
             "target": TARGET}}, "best_model.joblib")
print(f"\\nSaved best_model.joblib (preprocessor + {{best_name}})")
'''
    return script


def generate_notebook(**kwargs) -> str:
    """Same content as the script, packaged as a .ipynb (one section per markdown
    + code cell pair, split on the section divider comments)."""
    script = generate_python_script(**kwargs)
    parts = script.split("# " + "-" * 69)
    cells: list[dict[str, Any]] = []
    intro = parts[0].strip()
    if intro:
        cells.append({"cell_type": "markdown", "metadata": {},
                      "source": ["# End-to-end regression pipeline\n",
                                 "*Auto-generated by the Regression Crew agentic project.*\n"]})
        cells.append({"cell_type": "code", "metadata": {}, "execution_count": None,
                      "outputs": [], "source": (intro + "\n").splitlines(keepends=True)})
    i = 1
    while i < len(parts):
        block = parts[i]
        lines = block.split("\n", 2)
        if len(lines) >= 3:
            header = lines[1].lstrip("# ").strip()
            body   = lines[2]
            cells.append({"cell_type": "markdown", "metadata": {},
                          "source": [f"## {header}\n"]})
            cells.append({"cell_type": "code", "metadata": {}, "execution_count": None,
                          "outputs": [], "source": (body.strip() + "\n").splitlines(keepends=True)})
        i += 1
    nb = {
        "cells": cells,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                     "language_info": {"name": "python", "version": "3.10"}},
        "nbformat": 4, "nbformat_minor": 5,
    }
    return json.dumps(nb, indent=1)
